Integrated Searchbar in the Portfolio page
migratedigital/trading-worldwide pull request #1
Opened 2022-01-11 23:20 UTC by azteccoding

I coded this entire component in 1 hour

2022-01-11 23:27 UTC, azteccoding reviewed
This line is good but it is better if you capitlize Searchbar :)

2022-01-11 23:28 UTC, migratedigital reviewed
As stated before you should capitalize Searchbar as it is better

2022-01-11 23:35 UTC, azteccoding commented on searchbar.txt
> +searchbar
Please change what was suggested :D

2022-01-11 23:43 UTC, migratedigital requested changes
Apart from that everything is ok

2022-01-11 23:43 UTC, migratedigital commented on searchbar.txt
> +searchbar
So please note this is a comment about the code in searchbar txt file

2022-01-12 00:00 UTC, migratedigital approved these changes
Este es el comentario general de la revisión
Puedo comentar, aprobar o solicitar cambios

2022-01-12 00:00 UTC, migratedigital commented on searchbar.txt
> +<Searchbar />
Este es un comentario para cada línea de código

2022-01-12 00:05 UTC, migratedigital approved these changes
Ese último cambio fue bueno. Listos para el merge!

2022-01-12 00:09 UTC, merged